name: first-pipeline
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print start message 
        run: echo "Hi getting started with GA"; mkdir actdir
      - name: second step
        run: echo "listing the current directory contents"; ls
